### PR TITLE
Do not expect uninitialized counters in output

### PR DESCRIPTION
**Pull request by Tieske**
The problem was with `kong_enterprise_license_errors`.

- `kong_enterprise_license_errors` was not initialized, but was tested to be `0`, this caused the CI failure.
- `kong_nginx_metric_errors_total` was initialized, and tested to be `0`

For consistency the following changes were made:
- `kong_nginx_metric_errors_total` no longer initialized
- both of them tested to be absent instead of `0`

### CODE REVIEW

**Comment by Tieske** [comment]
@fffonion @hbagdi please check this one carefully, I'm not enough into Prometheus to know whether not-initializing actually poses an issue (some others were not, so I assumed it to be ok).

**Comment by Tieske** [comment]
this builds on top of the other PR, which has non-controversial fixes.

**Comment by Tieske** [comment]
The only consistent failure remaining is the one against Kong `master` branch. The fix for that one is in https://github.com/Kong/kong/pull/7529

**Comment by fffonion** [comment]
I think technically having consistency is good, but since `prometheus.lua` is a vendored 3rd library, I don't
feel it's a good idea to diverage its behaviour here from the upstream.
@Tieske How about we initialize `kong_enterprise_license_errors` instead, Will that solve the problem here?

**Comment by Tieske** [comment]
> How about we initialize kong_enterprise_license_errors instead, Will that solve the problem here?

that was the alternative, didn't know the lib was "vendored".

**Comment by Tieske** [comment]
replaced by #144

**Pull request closed without merging**
