### PR TITLE
perf(prometheus) use tablepool to recycle small Lua tables

### PR DESCRIPTION
**Pull request by WALL-E**

### CODE REVIEW

**Comment by hbagdi** [comment]
Thanks for the PR!

@WALL-E Did you do any benchmarking to measure the performance gains?

cc @fffonion

**Comment by WALL-E** [comment]
Performance improvement of nearly 18%

## environmental

* Host
  * aliyun ecs.c5.xlarge (4 vCPU 8 GiB )
* OS
  * CentOS 7.6
* Client
  * wrk 4.1.0-4-g0896020 [epoll]
* Gateway
  * Kong 2.0.2
* Backend
  * go-httpbin

## kong.conf

```
nginx_worker_processes = 1
database = off
declarative_config = /root/apis.yaml
```

## /root/apis.yaml

```
_format_version: "1.1"
services:
 - name: httpbin-service
   url: http://172.21.206.250:8080
   routes:
   - name: httpbin-route
     paths:
     - /
plugins:
 - name: prometheus
```

## Before optimization

> wrk -c 100 -t 4 -d 120

* api: /bytes/128
  * Requests/sec:   **2186.48**
* api: /bytes/1024
  * Requests/sec:   **2182.26**

## After optimization

> wrk -c 100 -t 4 -d 120

* api: /bytes/128
  * Requests/sec:   **2579.99**
* api: /bytes/1024
  * Requests/sec:   **2587.16**

**Comment by fffonion** [comment]
Hi @WALL-E, thanks for the PR!

The optimization looks effective to me. However we have an ongoing optimizing #79 that removes the `full_metric_name` function call from hot path. The majority CPU time is actually taken in string creation and non JIT-able `gsub`.
But I believe even in #79 there's still space for further optimizing by resuing tables (in fact I made a similar manual approach in https://github.com/Kong/kong-plugin-prometheus/pull/79/files#diff-e042610de3f69c255ec585c6866b1178R69). If possible, could you rebase your work on that PR and compare performance gain?

**Comment by WALL-E** [comment]
prometheus plugin does need more optimization @fffonion 
image

**Comment by fffonion** [comment]
@WALL-E Indeed, actually your flamegraph also reveals the issue here, there's a big chunk of stacktrace being took by builtin#90, which in the version of luajit kong linked is string:gsub. And because it's not JIT-able, we are removing it from hot path (per `inc()` call). You can compare it with our current optimization in https://github.com/Kong/kong-plugin-prometheus/pull/79#issuecomment-598159210.
So my thought here was let's still take the tablepool optimization, but not in the `full_metric_name` function as it's not going to give us much boost after it's off the hot path.

**Comment by WALL-E** [comment]
duplicate, move to #79

**Pull request closed without merging**
