### PR TITLE
feat(grafana) show cache in subsystem, worker vm memories and upstream

### LINKED ISSUE #101: Remove kong_process_events from Grafana dashboards
It's supposed to be full, but this looks like a problem on the dashboard. No real reason to report on it since it's not something users should care about under normal conditions.

### PR DESCRIPTION
**Pull request by fffonion**
status
FireShot Capture 074 - Kong (official) - Grafana_ - http___localhost_3000_d_mY9p7dQmz_kong-official

Fix #101 as well

### CODE REVIEW

**Comment by hbagdi** [comment]
Should we have Lua VM usages as graph with time on the x axis?
It seems like a useful metric to have a historical view while debugging.

**Comment by fffonion** [comment]
updated code and screenshot

**Comment by joelsdc** [comment]
Looking forward for this to be merged!! 💪

**Review by hbagdi — APPROVED** [review]
Rubber stamp approval only

**Pull request merged**
